# Generated by Django 4.2.11 on 2024-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
